sudo: false
language: node_js
script:
  - npm run build
  - npm test
node_js:
  - "6"
  - "7"
# the following config is needed for the "microtime" native node module
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
